### PR TITLE
fix: update yaml validation rules for project data, and fix inconsistent yaml formatting and remove unused fields across project data

### PR DESCRIPTION
**Pull request by 0xdevant**
As mentioned this PR does the following things:
1. update the yaml validation rules for project data to ensure consistent types validation to pass schema test
2. fix all project data yaml files that have inconsistent formatting with above yaml validation rule
3. remove unused or non-existent fields across all project data

### CODE REVIEW

**Comment by 0xdevant** [comment]
I am able to get the project built without any problems locally, but I think something is off on the index.yaml of Auth3 project on our main branch? 
image

Since the error from the GH action seems to be pointing to a formatting error for that file, could @Msiusko help look into this? I am not sure if this is the change that causes the action to keep failing.

The change was merged 2 weeks ago:
https://github.com/web3privacy/explorer-data/pull/28/files

**Comment by Msiusko** [comment]
@0xdevant so there's a syntax error - like we need to put the description like this "description: 'project description'.

And the whole build right now depends on each project's correct description (which is insane).

How do you think it's possible to 
- separate each project deployment
- so one correctly syntax can be deployed 
- while non-correct - failed 

It seems that now no project can be deployed on front before we fix all syntax errors within all projects - Auth3 example https://explorer.web3privacy.info/project/auth3 - I updated everything, but front is old

**Comment by Msiusko** [comment]
Otherwise this what happens https://github.com/web3privacy/explorer-data/actions?page=2&query=is%3Afailure

**Comment by 0xdevant** [comment]
Sure, then we need to work on `build.js` to catch all syntax errors during the build and continue the deployment for the rest

**Pull request merged**
